In [2]:
import datetime as dt
import pandas as pd
import numpy as np

In [198]:
Stock_Price = pd.read_csv('./Stock Market/NIKKEI.csv')
Stock_Price

,1332.T-open,1332.T-high,1332.T-low,1332.T-close,1332.T-volume,1333.T-open,1333.T-high,1333.T-low,1333.T-close,1333.T-volume,...,9983.T-open,9983.T-high,9983.T-low,9983.T-close,9983.T-volume,9984.T-open,9984.T-high,9984.T-low,9984.T-close,9984.T-volume
0,2.371402,2.384152,2.333154,2.345903,1754000.0,NaN,NaN,NaN,NaN,NaN,...,204.884059,205.266543,202.716648,203.736606,370500.0,38.503414,38.694656,38.095431,38.133679,3137300.0
1,2.354572,2.367369,2.316183,2.316183,2409900.0,NaN,NaN,NaN,NaN,NaN,...,204.233556,207.688636,204.105591,206.664908,510700.0,37.967479,38.645698,37.916292,38.453749,3705800.0
2,2.317761,2.330566,2.253734,2.253734,1825900.0,NaN,NaN,NaN,NaN,NaN,...,205.525188,208.854568,205.141028,208.342355,463000.0,39.568401,40.720878,39.504374,40.720878,12509200.0
3,2.255220,2.331668,2.242479,2.293444,1491900.0,NaN,NaN,NaN,NaN,NaN,...,206.792198,206.792198,200.294106,201.823069,768100.0,40.326390,40.581217,39.944149,40.198976,6587100.0
4,2.305167,2.305167,2.189909,2.215522,2517700.0,NaN,NaN,NaN,NaN,NaN,...,202.982766,211.178915,202.982766,208.745684,853200.0,39.700099,40.212359,39.572035,39.764132,4755900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427,4.339446,4.398087,4.339446,4.361436,871800.0,18.039487,18.310703,18.039487,18.244732,215900.0,...,584.945590,591.322817,583.113054,584.798987,558100.0,39.729387,40.418421,39.707397,40.352450,7022000.0
2428,4.390755,4.456727,4.383425,4.434736,1474400.0,18.325356,18.471959,18.288705,18.376667,197000.0,...,583.919144,587.437612,576.662303,584.285651,565700.0,40.293793,42.075017,40.242482,41.642539,19044800.0
2429,4.426517,4.426517,4.346168,4.368081,1252600.0,18.312341,18.326950,17.954421,18.005553,178500.0,...,582.167368,582.240413,572.525449,573.986346,684700.0,41.241116,41.635558,40.795543,41.547905,10978600.0
2430,4.401626,4.408962,4.372282,4.401626,894000.0,18.090682,18.237403,18.046666,18.193387,223500.0,...,582.188379,584.902715,573.678569,578.740438,548100.0,42.189584,42.622410,41.382619,41.492660,12618700.0
2431,4.439987,4.462298,4.417675,4.447424,870900.0,18.436729,18.466477,18.287985,18.429291,176000.0,...,589.543957,597.724837,587.833409,596.460519,722100.0,42.183592,42.860374,41.402690,41.685302,12677200.0

In [199]:
open = pd.read_excel('./Stock Market/NIKKEI open.xlsx')
open

,Date,1332.T,1333.T,1605.T,1721.T,1801.T,1802.T,1803.T,1808.T,1812.T,...,9502.T,9503.T,9531.T,9532.T,9602.T,9613.T,9735.T,9766.T,9983.T,9984.T
0,37260,NaN,NaN,NaN,NaN,2.154556,2.832137,3.380292,0.159879,2.778844,...,18.043453,14.381469,2.588512,2.360114,108.717512,3585.850712,51.313448,29.996288,91.283121,16.673064
1,37263,NaN,NaN,NaN,NaN,2.126849,2.805306,3.369417,0.152462,2.751945,...,17.685627,14.346703,2.576613,2.294558,109.163010,3788.688261,51.760952,29.806380,91.096227,17.418818
2,37264,NaN,NaN,NaN,NaN,2.117184,2.850937,3.439469,0.160509,2.751575,...,17.426641,14.178254,2.484061,2.292979,109.604400,3791.058755,51.209866,29.655863,88.661858,17.235559
3,37265,NaN,NaN,NaN,NaN,2.008520,2.736135,3.145418,0.151586,2.675500,...,16.826090,13.900473,2.455700,2.266217,106.110480,3660.811565,50.478271,28.346657,79.961826,17.091367
4,37266,NaN,NaN,NaN,NaN,1.888315,2.678248,3.129638,0.157987,2.603016,...,16.588584,13.692165,2.392367,2.189242,105.324344,3686.352049,50.179527,28.437573,64.323082,17.002358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4986,44767,4.339446,18.039487,10.152251,19.512847,31.336371,7.205533,5.658872,11.896826,11.207792,...,9.895696,9.785744,18.992406,17.555698,38.996373,14.433056,65.912666,56.442118,584.945590,39.729387
4987,44768,4.390755,18.325356,10.438123,19.476188,31.336359,7.198200,5.629549,12.028764,11.127156,...,9.998314,9.771080,19.204973,17.519040,38.996358,14.484361,65.663416,56.368795,583.919144,40.293793
4988,44769,4.426517,18.312341,10.569588,19.422623,31.117101,7.143785,5.587930,11.847873,11.132033,...,9.788008,9.700355,19.429927,17.567284,38.640720,14.455574,65.411653,56.536705,582.167368,41.241116
4989,44770,4.401626,18.090682,10.791319,19.381826,31.288224,7.292027,5.670761,11.928406,11.165458,...,10.138412,9.734929,18.971007,17.386422,39.027749,14.664750,65.232095,56.707613,582.188379,42.189584
4990,44771,4.439987,18.436729,11.170620,19.857227,31.905432,7.399978,5.771239,12.107702,11.289614,...,10.486401,9.950925,19.708483,17.834318,39.268224,14.874327,67.194773,57.935504,589.543957,42.183592

In [200]:
name = open.columns
name

Index(['Date', '1332.T', '1333.T', '1605.T', '1721.T', '1801.T', '1802.T',
       '1803.T', '1808.T', '1812.T',
       ...
       '9502.T', '9503.T', '9531.T', '9532.T', '9602.T', '9613.T', '9735.T',
       '9766.T', '9983.T', '9984.T'],
      dtype='object', length=226)

In [201]:
for n in name:
    if n != "Date":
        Stock_Price[n + "-volume"] = Stock_Price[n + "-volume"]/100000

In [202]:
Stock_Price

,1332.T-open,1332.T-high,1332.T-low,1332.T-close,1332.T-volume,1333.T-open,1333.T-high,1333.T-low,1333.T-close,1333.T-volume,...,9983.T-open,9983.T-high,9983.T-low,9983.T-close,9983.T-volume,9984.T-open,9984.T-high,9984.T-low,9984.T-close,9984.T-volume
0,2.371402,2.384152,2.333154,2.345903,17.540,NaN,NaN,NaN,NaN,NaN,...,204.884059,205.266543,202.716648,203.736606,3.705,38.503414,38.694656,38.095431,38.133679,31.373
1,2.354572,2.367369,2.316183,2.316183,24.099,NaN,NaN,NaN,NaN,NaN,...,204.233556,207.688636,204.105591,206.664908,5.107,37.967479,38.645698,37.916292,38.453749,37.058
2,2.317761,2.330566,2.253734,2.253734,18.259,NaN,NaN,NaN,NaN,NaN,...,205.525188,208.854568,205.141028,208.342355,4.630,39.568401,40.720878,39.504374,40.720878,125.092
3,2.255220,2.331668,2.242479,2.293444,14.919,NaN,NaN,NaN,NaN,NaN,...,206.792198,206.792198,200.294106,201.823069,7.681,40.326390,40.581217,39.944149,40.198976,65.871
4,2.305167,2.305167,2.189909,2.215522,25.177,NaN,NaN,NaN,NaN,NaN,...,202.982766,211.178915,202.982766,208.745684,8.532,39.700099,40.212359,39.572035,39.764132,47.559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427,4.339446,4.398087,4.339446,4.361436,8.718,18.039487,18.310703,18.039487,18.244732,2.159,...,584.945590,591.322817,583.113054,584.798987,5.581,39.729387,40.418421,39.707397,40.352450,70.220
2428,4.390755,4.456727,4.383425,4.434736,14.744,18.325356,18.471959,18.288705,18.376667,1.970,...,583.919144,587.437612,576.662303,584.285651,5.657,40.293793,42.075017,40.242482,41.642539,190.448
2429,4.426517,4.426517,4.346168,4.368081,12.526,18.312341,18.326950,17.954421,18.005553,1.785,...,582.167368,582.240413,572.525449,573.986346,6.847,41.241116,41.635558,40.795543,41.547905,109.786
2430,4.401626,4.408962,4.372282,4.401626,8.940,18.090682,18.237403,18.046666,18.193387,2.235,...,582.188379,584.902715,573.678569,578.740438,5.481,42.189584,42.622410,41.382619,41.492660,126.187
2431,4.439987,4.462298,4.417675,4.447424,8.709,18.436729,18.466477,18.287985,18.429291,1.760,...,589.543957,597.724837,587.833409,596.460519,7.221,42.183592,42.860374,41.402690,41.685302,126.772

In [55]:
Stock_Price.to_csv("./Stock Market/HangSeng_final.csv",index=False,header=True)

In [11]:
Stock_Price = pd.read_csv('./Stock Market/FTSE_close.csv')

In [12]:
Stock_Price

,AAL.L,ABDN.L,ABF.L,ADM.L,AHT.L,ANTO.L,AV_.L,AVV.L,AZN.L,BA_.L,...,STJ.L,SVT.L,TSCO.L,TW_.L,ULVR.L,UTG.L,UU_.L,VOD.L,WPP.L,WTB.L
0,31.862928,5.317960,22.843138,24.187950,4.833177,21.701697,7.022310,28.261525,64.061051,6.466130,...,6.218459,39.078375,6.138411,0.713191,44.710278,3.310546,14.000879,5.155013,12.974823,44.885168
1,31.538927,5.288320,22.782806,23.664091,4.679936,21.379716,6.841311,28.036079,63.822713,6.378794,...,6.149352,38.634136,6.127139,0.699450,44.997149,3.314197,13.804253,5.152423,12.694099,44.237360
2,31.790663,5.349146,23.160027,24.555600,4.766059,21.843113,7.004281,28.051015,64.695858,6.434825,...,6.151699,38.246431,6.122278,0.732455,45.256080,3.357503,13.648531,5.311138,12.826679,43.444246
3,30.415934,5.308662,22.785854,23.623313,4.581352,20.518991,6.613014,27.824452,63.974975,6.306338,...,5.985666,37.585290,5.980387,0.722596,44.374579,3.342195,13.453272,5.241433,12.413867,42.308394
4,31.155671,5.468811,22.840669,24.740071,4.841328,21.449193,7.094682,28.253768,65.341577,6.417906,...,6.210731,38.442162,6.068211,0.747094,45.272730,3.337482,13.702779,5.298853,12.870127,43.647391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427,32.712202,1.906514,20.323759,20.815221,49.601720,12.885899,4.764786,27.953410,129.578199,9.359358,...,14.216443,34.678051,3.174126,1.522334,46.946625,14.264390,12.790004,1.546548,10.428588,31.873120
2428,33.156882,1.850084,19.838687,21.544139,49.150768,13.010852,4.731876,27.636761,132.820370,9.485447,...,13.800302,35.061203,3.118024,1.488504,48.596346,14.222145,12.938536,1.474764,10.278513,31.541825
2429,33.412588,1.888564,20.089695,21.781395,49.908172,12.991777,4.775291,28.054533,131.988753,9.415728,...,13.852678,34.592564,3.143793,1.493031,48.108106,13.112183,12.744946,1.457150,10.470482,32.208531
2430,34.592168,1.957933,20.217782,22.911459,53.472232,13.565675,4.792678,27.131351,132.190849,9.478339,...,14.623689,35.400880,3.170391,1.537159,48.279454,13.851461,13.030588,1.444735,10.570403,31.509337
2431,35.906824,2.016868,20.351258,23.345522,55.880756,14.101036,4.820035,28.688944,131.991051,9.372290,...,14.940890,35.906824,3.196316,1.547036,48.729821,14.180153,13.267267,1.470354,10.757441,31.622349

In [13]:
Stock_Price.isnull().values.any()

False

In [14]:
Stock_Price.isnull().any()

AAL.L     False
ABDN.L    False
ABF.L     False
ADM.L     False
AHT.L     False
          ...
UTG.L     False
UU_.L     False
VOD.L     False
WPP.L     False
WTB.L     False
Length: 87, dtype: bool

In [53]:
Stock_Price = Stock_Price.fillna(method = "bfill")
Stock_Price

,0001.HK-open,0001.HK-high,0001.HK-low,0001.HK-close,0001.HK-volume,0002.HK-open,0002.HK-high,0002.HK-low,0002.HK-close,0002.HK-volume,...,3968.HK-open,3968.HK-high,3968.HK-low,3968.HK-close,3968.HK-volume,3988.HK-open,3988.HK-high,3988.HK-low,3988.HK-close,3988.HK-volume
0,23.571399,23.968933,23.571399,23.922164,48.24205,34.352664,34.926513,34.274412,34.900429,32.33927,...,2.730925,2.777674,2.727029,2.750404,168.42585,0.503017,0.503017,0.491201,0.492889,2368.39816
1,23.786835,24.067506,23.763446,23.880392,39.14209,34.725106,35.038180,34.699017,34.959912,32.54723,...,2.739290,2.805532,2.735393,2.789945,138.61663,0.494681,0.503122,0.492992,0.501434,3133.98558
2,24.094242,24.234597,23.953887,24.187812,35.73972,34.573373,35.069142,34.573373,34.886490,19.66332,...,2.739670,2.813716,2.739670,2.802024,129.98536,0.498126,0.504881,0.496438,0.501504,3840.89509
3,23.951192,24.185090,23.810853,23.927802,19.59424,35.039106,35.065196,34.830384,34.856474,17.56638,...,2.813399,2.813399,2.754949,2.774432,82.67799,0.504824,0.504824,0.494694,0.498070,2619.50406
4,24.209843,24.326799,23.554891,24.303408,52.59173,34.649704,34.936712,34.649704,34.884528,11.89389,...,2.762898,2.762898,2.708341,2.759001,157.21831,0.493033,0.499787,0.491345,0.498098,2340.70956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427,17.855331,17.924138,17.786524,17.889734,24.09127,49.855295,49.968947,49.476455,49.893179,24.32071,...,12.397477,12.657868,12.368545,12.484274,147.59578,0.872861,0.882384,0.872861,0.882384,1259.31662
2428,17.889826,18.337071,17.855422,18.251063,45.56591,49.628244,49.931318,49.590360,49.666129,25.38403,...,12.585602,12.918324,12.585602,12.860459,159.81682,0.882388,0.885562,0.879214,0.882388,2168.10094
2429,18.113669,18.199679,17.907245,18.044861,23.53831,49.666733,50.121348,49.628848,50.121348,18.38745,...,12.730418,12.817217,12.658086,12.715952,108.89683,0.882399,0.888747,0.882399,0.888747,1937.71598
2430,18.044584,18.061786,17.872567,17.992979,27.40804,50.310000,50.385768,49.779623,50.044811,16.30015,...,12.730223,12.730223,12.411968,12.455366,233.83346,0.885559,0.891907,0.882385,0.888733,1419.50903
2431,17.991697,18.215303,17.785291,17.905694,52.79489,49.927600,50.457939,49.851838,50.382176,26.36179,...,12.512339,12.656990,12.136245,12.266432,250.55103,0.888670,0.895018,0.879149,0.885496,2194.73348

In [72]:
Stock_Price.to_csv("./Stock Market/DAX_final.csv",index=False,header=True)